### ISSUE TITLE
:path variable returns absolute path on windows instead of relative

### ISSUE THREAD

**Issue by tuur29** [van-nguyen/webpack-cdn-plugin#7]
I get the following output in my index.html file

`<script type=text/javascript src="//unpkg.com/vue@2.4.1/C:\project\node_modules\vue\dist\vue.runtime.common.js"></script>`

**Comment by tuur29** [comment]
I made it work by manually adding a path object to the config, not very intuitive though, but on the other hand you have to do it anyways when you want to load minified versions.

**Comment by van-nguyen** [comment]
Hi @tuur29, that's a good one, thanks for reporting. Looking at the code it seems to assume all path separators are forward slashes, I will get this fix soon, hopefully this coming week. However, a PR is welcome if you need the fix soon :)

**Comment by van-nguyen** [comment]
@tuur29 I don't have a Windows machine to check, but this should fix it. Can you please verify?

**Comment by tuur29** [comment]
I'm afraid not, after removing one of the paths I get the following error:

> 
> ERROR in   TypeError: Cannot read property '1' of null
> 
>   - src.js:77 modules.map
>     [project]/[webpack-cdn-plugin]/src.js:77:90

Seems like you forgot that backslash has a meaning in regex. After changing it to this it works for me:
> p.path = p.path || require.resolve(p.name).match(/[\/\\]node_modules[\/\\].+?[\/\\](.*)/)[1].replace(/\\/g, '/');

(I'm afraid I'm not that great with the whole git thing, so I'll let you handle that)

**Comment by van-nguyen** [comment]
Ahhh I see, didn't realise you have to escape backslash inside square brackets, didn't have to escape the forward slash though. Have published, hopefully this should be it 👍
